### ISSUE TITLE
Cannot install Valhesia

### ISSUE THREAD

**Issue by LucaFagnoni** [Khytwel/Valhelsia#11]
Hello i'm trying to install Valhesia mod through Twitch Launcher but everytime it returns an error "Impossible to find specified file" (rough translation).
![image](https://user-images.githubusercontent.com/23366996/80532593-af77f800-899c-11ea-841b-25ea0d5d2362.png)

Do you have any solution to this?

**Comment by Balthizar01** [comment]
You can join our Discord and get better help there.

https://discord.gg/wvXhcb
