### ISSUE TITLE
Error with installing

### ISSUE THREAD

**Issue by w26i** [Khytwel/Valhelsia#14]
everytime i install the modpack i get "Unable to get Addon: RFTOOLS"

**Comment by DannehSC** [comment]
Same, except I also see Serene Seasons and Hwyla under the "unable to get" error.

**Comment by b0bst3r** [comment]
Try a different launcher as Twitch has issues with 1.15 packs and missing Forge libraries 
![80292622-e4dfd400-8757-11ea-8721-5e78f7861ceb](https://user-images.githubusercontent.com/2760085/80660194-f04a3c80-8a82-11ea-8c8d-d18960d6ca8e.png)

**Comment by Vaelzan** [comment]
CurseForge / Twitch have been having issues for several days now causing this error. It isn't anything to do with the mod pack itself and it isn't something we can fix.
