### ISSUE TITLE
Issues with the server pack(2.1.7)

### ISSUE THREAD

**Issue by cafciel** [Khytwel/Valhelsia#15]
Server isn't starting for me...
One issue is with Solar Flux Reborn, it just crashes the Server.
The next issue comes with structurize, it seems any structure cannot be loaded on the server. (and therefore I also deactivated minecolonies) then it starts and I can connect to it.

Details to my server:
- Ubuntu 20.04 freshly installed for this modpack
- openjdk-11-sdk

**Comment by Vaelzan** [comment]
The issue with Solar Flux Reborn is that modded Minecraft requires Java 8, not Java 11.

Structurize and MineColonies need to be updated to the latest versions as there happened to be a breaking bug when the pack was last updated.

Please use the Discord for support involving crashes in future, as per the README https://github.com/Khytwel/Valhelsia/issues/5

https://discordapp.com/invite/reQZEXu

**Comment by b0bst3r** [comment]
Modded Minecraft does not support Java 11 (openjdk-11-sdk) uninstall and install Java 8 - 64bit
