### ISSUE TITLE
Valhelsia (2): Error while joining

### ISSUE THREAD

**Issue by iInjection** [Khytwel/Valhelsia#17]
Sup. Just installed the Server Pack of v2.1.7 on my Dedicated Server, For me joining went fine, but a friend of mine can't; This is the error he is getting (still, after reinstalling Valhelsia + reinstalling Java 
![WhatsApp Image 2020-05-02 at 17 01 44](https://user-images.githubusercontent.com/22277062/80867850-b782b100-8c96-11ea-9243-6172bd49a341.jpeg)

**Comment by Vaelzan** [comment]
Please come to Discord for support. We don't use the GitHub issues for technical support. If you post the logs from your friend's game as well as the server (latest.log) we can help you there.

https://discordapp.com/invite/reQZEXu
