### ISSUE TITLE
Server Keeps Saying Prearing spawn area: 100% over and over again and doesn't want to load the world

### ISSUE THREAD

**Issue by FallenNations** [Khytwel/Valhelsia#18]
When I try to the load the server it just says this multiple times and doesn't want to finished the start up anyone got any ideas to why this is happening.
I even tried it on and fresh install of the server and the same instance happened

![Capture](https://user-images.githubusercontent.com/64723511/80907794-bcbc1c00-8ce7-11ea-95e5-5afc505e27e7.PNG)

**Comment by Khytwel** [comment]
This comes from a bug in Mekanism, you can fix this problem by changing this: allowChunkloading = false in the file "general.toml" which is in the Mekanism folder in config.

**Comment by Vaelzan** [comment]
I think this particular one might actually be Guard Villagers which can cause a similar issue in some cases (involving raids), but it is impossible to know for sure without the full log.

**Comment by FallenNations** [comment]
@Khytwel The problem is still happening, i changed the config file and it is still saying the same thing.

**Comment by FallenNations** [comment]
[Log.txt](https://github.com/Khytwel/Valhelsia/files/4572247/Log.txt) Here is the full log
@Khytwel 
@Vaelzan

**Comment by Vaelzan** [comment]
Yep, it's caused by Guard Villagers like I mentioned (checked the log to be sure). You'll need to remove that mod then add it back in later once the world opens again.

**Comment by FallenNations** [comment]
I removed the mod and the problem still happened

**Comment by Vaelzan** [comment]
Could be that it was both Mekanism and Guard Villagers, since both seem to be causing issues in that log. Try removing the file "mekanism_force_chunks.dat" in the data subfolder of the world.
