### ISSUE TITLE
Refined Pipes & Storage Drawers Incompatible

### ISSUE THREAD

**Issue by Esheon** [Khytwel/Valhelsia#25]
Client Version: 2.1.8, installed on MultiMC 5
Server Version: 2.1.8, hosted on mtxserv.com

It seems that Refined Pipes cannot input into Storage Drawers. One of my players was using a Refined Pipe to input items into a 1x1 Oak Storage Drawer, and the server started getting this message repeatedly:

[05May2020 05:51:57.629] [Server thread/WARN] [com.raoulvdberge.refinedpipes.network.pipe.attachment.extractor.ExtractorAttachment/]: No destination found from BlockPos{x=-327, y=61, z=-421}

After a while, the server shut down due to excessive CPU usage while nobody was online.

The error stops if you destroy either the pipe or the storage drawer.

We had the same issue on client/server version 2.1.7 yesterday so I updated to 2.1.8, which did not solve the problem. For the time being, I have alerted my players to avoid connecting Refined Pipes to any Storage Drawer block.

**Comment by Khytwel** [comment]
For the compatibility issue, I invite you to report the problem directly to the developers concerned.
https://github.com/raoulvdberge/refinedpipes/issues
