### ISSUE TITLE
v2.18 is installing incorrectly

### ISSUE THREAD

**Issue by nephilese** [Khytwel/Valhelsia#26]
Using both the twitch launcher as well as a manual download, the recent update is mis-identifying as 2.17 and is incompatible with the 2.18 server update.

Update: I installed also through MultiMC5 to similar results. "Failed to connect to the server. Connection closed - mismatched mod channel list"

**Comment by Khytwel** [comment]
This has nothing to do with the mis-identifying of the version. You must have an old version for the server or have extra mods on your server or client.
