### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by LegatusDragon** [Khytwel/Valhelsia#3]
forge-client.jar file is missing. I am having this issue with every 1.15+ pack on the twitch app, so imagine it is not your problem but FTB and Twitch help told me to seek out the pack author...
[04-25 Crash Log.txt](https://github.com/Khytwel/Valhelsia/files/4534311/04-25.Crash.Log.txt)

**Comment by Khytwel** [comment]
![image](https://user-images.githubusercontent.com/54046029/80292622-e4dfd400-8757-11ea-8721-5e78f7861ceb.png)
Next time, come to our discord server and ask for help. The GitHub is just for reporting bugs in game.

https://discordapp.com/invite/reQZEXu
