### ISSUE TITLE
Vanilla maps causing crash on join

### ISSUE THREAD

**Issue by AlexGPTB** [Khytwel/Valhelsia#31]
My friends and I are doing a server together and one friend used a vanilla map and it caused his game to have an internal server error every time he tries to join now.

**Comment by Vaelzan** [comment]
You'll need to edit their inventory to remove the map. Make a backup first. I think something like https://www.universalminecrafteditor.com/ will work but I haven't tested it myself.

The bug has proven difficult to track down the source of. I initially thought it fixed along with some related issues but there appears to be another issue that I can't track down yet.

**Comment by Vaelzan** [comment]
This is the same issue as #13 so I will close this for now and edit the title of that issue.

**Comment by Vaelzan** [comment]
Feel free to use our Discord server for support if you need any assistance with the fix.
