### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by Reivax69008** [Khytwel/Valhelsia#4]
Hello,
I'll try to install the version 1.15.2.
But there is many error and the server can't start.
Under the crash report
[crash-2020-04-26_22.18.51-server.txt](https://github.com/Khytwel/Valhelsia/files/4536414/crash-2020-04-26_22.18.51-server.txt)

**Comment by Khytwel** [comment]
Come to our discord server and ask for help. The GitHub is just for reporting bugs in game.

https://discordapp.com/invite/reQZEXu

**Comment by b0bst3r** [comment]
@Reivax69008  Java Version: 11.0.7, Ubuntu <<-- Uninstall that and install Java 8 64 bit
