### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by Cooper1dog** [Khytwel/Valhelsia#6]
Valhelsia 2 is crashing as soon as Play is hit in the most recent Minecraft Launcher through the Twitch app. No Logs have been generated.

**Comment by b0bst3r** [comment]
Read the 2nd post here - https://github.com/Khytwel/Valhelsia/issues/3

**Comment by Khytwel** [comment]
Come to our discord server and ask for help. The GitHub is just for reporting bugs in game.

https://discordapp.com/invite/reQZEXu
