### ISSUE TITLE
Treasure Maps crashing the game

### ISSUE THREAD

**Issue by FERegis** [Khytwel/Valhelsia#7]
[crash-2020-04-27_15.25.10-server.txt](https://github.com/Khytwel/Valhelsia/files/4541433/crash-2020-04-27_15.25.10-server.txt)
I have a problem with the modpack, when i open the treasure map my game crash.

**Comment by Vaelzan** [comment]
Hello. You're using an old version of the modpack that was known to have broken treasure maps. Please update before reporting issues with the pack.

**Comment by FERegis** [comment]
Ok, i'll try it

**Comment by FERegis** [comment]
[crash-2020-04-27_16.03.39-server.txt](https://github.com/Khytwel/Valhelsia/files/4541564/crash-2020-04-27_16.03.39-server.txt)
So, i updated my modpack instance and i got that error again

**Comment by Vaelzan** [comment]
Is that with a new world? The existing chunks in that world will continue to have that issue due to it being generated in the previous update. It won't be fixed except with newly generated maps + buried treasure.

**Comment by Vaelzan** [comment]
You can remove the current treasure map from your inventory using NBTExplorer or similar if that helps you get back into the world.

**Comment by FERegis** [comment]
To fix it i opened a server and put my map online, so i lost my itens and waypoints, but idk, i loved this modpack, i guess it is the best modpack i ever player, you already have a modlist that will be implemented in the modpack? im very curious
